accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),    
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='home'),
    path('user/<str:username>/', views.UserPostList.as_view(), name='user_post'),
    path('create/new/', views.CreatePostView.as_view(template_name='posts/create_post.html'), name='create'),
    path('update/<pk>/', views.UpdatePostView.as_view(template_name='posts/update_post.html'), name='update'),
    path('remove/<pk>/', views.DeletePostView.as_view(template_name='posts/delete_post.html'), name='delete'),
    path('category/', views.CategoryPostView.as_view(), name="category"),
    path('add_category/', views.AddCategory.as_view(), name="add_category"),
    path('update_category/<pk>/', views.EditCategory.as_view(), name="edit_category"),
    path('remove_category/<pk>/', views.RemoveCategory.as_view(), name="remove_category"),
    path('category_posts/<str:cats>/', views.categoryposts, name="view_category"),
]

social/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('thanks/', views.thanks, name='thanks'),
    path('welcome/', views.welcome, name='welcome'),
    path('cancel/', views.cancel, name='cancel'),
    path('howto/', views.howto, name='howto'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth import models

# Create your models here.
class User(models.User, models.PermissionsMixin):

    def __str__(self):
        return f"@{self.username}"

posts/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model

User = get_user_model()

# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(User, related_name='posts', on_delete=models.CASCADE)

    title = models.CharField(max_length=20, blank=False)
    caption = models.TextField(max_length=255)
    flyer = models.FileField(upload_to='flyer', null=False, blank=False)
    event_date = models.DateField(blank=True, null=True)
    location = models.CharField(max_length=150, default='', blank=True, null=True)
    category = models.CharField(max_length=255, default='')
    created_at = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('posts:home')

    def __str__(self):
        return f"@{self.user}'s Post"

    class Meta:
        ordering = ['-created_at']
        unique_together = ['title']

class Category(models.Model):
    name = models.CharField(max_length=150, null=True, blank=False)

    def save(self, *args, **kwargs):
        self.name = self.name.lower()
        return super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return f"Category: {self.name}"

    def get_absolute_url(self):
        return reverse('posts:home')

    class Meta:
        ordering = ['name']

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCreateForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'password1', 'password2')

        def __init__(self, **kwargs):
            super().__init__(**kwargs)
            self.fields['username'].label = 'Display Name'
            self.fields['email'].label = 'Email Address'

posts/forms.py
from django import forms
from .models import Post , Category

# Create Forms Here

"""
    Due to migration issues, please comment the following before migrating. Once migrated, uncomment and migrate again
        - choices
        - choice_list
        - for item in choices:
            choice_list.append(item)
        - 'category' in the widgets


"""

class DateInput(forms.DateInput):
    input_type = 'date'

choices = Category.objects.all().values_list('name', 'name')

choice_list = []

for item in choices:
    choice_list.append(item)

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('flyer', 'title', 'caption', 'location', 'category', 'event_date')
        widgets = {
            'event_date': DateInput(),
            'category': forms.Select(choices=choice_list, attrs={'class': 'form-control'})
        }

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'

accounts/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView

from .forms import UserCreateForm
from django.urls import reverse_lazy
# Create your views here.

class SignUp(CreateView):
    form_class = UserCreateForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

posts/views.py
from curses.ascii import HT
from django.shortcuts import render
from django.contrib import messages
from django.views.generic import TemplateView, ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView,DeleteView
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404

from .models import Post, Category
from .forms import PostForm, CategoryForm

from django.contrib.auth import get_user_model
User = get_user_model()
# Create your views here.

class PostList(ListView):
    model = Post

class UserPostList(ListView):
    model = Post
    template_name = 'posts/user_posts.html'

class CategoryPostView(ListView):
    model = Category
    template_name = 'posts/category.html'

class AddCategory(CreateView):
    model = Category
    form_class = CategoryForm
    template_name = 'posts/add_category.html'
    success_url = reverse_lazy('posts:category')

class EditCategory(UpdateView):
    model = Category
    form_class = CategoryForm
    template_name = 'posts/edit_category.html'
    success_url = reverse_lazy('posts:category')

class RemoveCategory(DeleteView):
    model = Category
    template_name = 'posts/remove_category.html'
    success_url = reverse_lazy('posts:category')

def categoryposts(request, cats):
    category_posts = Post.objects.filter(category=cats.replace('-', ''))
    return render(request, 'posts/view_category_posts.html', {'cats': cats, 'category_posts': category_posts} )


class CreatePostView(LoginRequiredMixin, CreateView):
    form_class = PostForm
    model = Post
    success_url = reverse_lazy('posts:home')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

class UpdatePostView(LoginRequiredMixin, UpdateView):
    form_class = PostForm
    model = Post
    success_url = reverse_lazy('posts:home')


class DeletePostView(LoginRequiredMixin, DeleteView):
    
    model = Post
    success_url = reverse_lazy('posts:home')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id = self.request.user.id)

social/views.py
from django.shortcuts import render

# Create your views here

def thanks(request):
    return render(request, 'social/thanks.html')

def welcome(request):
    return render(request, 'social/welcome.html')

def cancel(request):
    return render(request, 'social/cancel.html')

def howto(request):
    return render(request, 'social/howto.html')

templates/accounts/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} {% load static %}

{% block head %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/side.css' %}">
{% endblock %}

{% block content %}
<div class="container" style="padding-top: 100px; padding-bottom: 100px;">
    <div class="container">
        <form method="POST" class="post-form">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" class="btn btn-success" value="Log In"> <br><br>

            <h3>Don't have an Account?</h3>
            <a class="btn btn-info" href="{% url 'accounts:signup' %}">Sign Up</a>
        </form>
    </div>
</div>
{% endblock %}

templates/accounts/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} {% load static %}

{% block head %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/side.css' %}">
{% endblock %}

{% block content %}
<div class="container" style="margin-top: 75px; ">
    <div class="container">
        <form method="POST" class="post-form">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" class="btn btn-success" value="Sign Up"> <br> <br>

            <h3>Already have an Account?</h3>
            <a class="btn btn-info" href="{% url 'accounts:login' %}" style="margin-bottom: 10px">Log In</a>
        </form>
    </div>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Social Events</title>
        <link rel="icon" type="image/x-icon" href="{% static 'images/favi.png' %}">
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        <link href='//spoqa.github.io/spoqa-han-sans/css/SpoqaHanSansNeo.css' rel='stylesheet' type='text/css'>
        {% block head %}
        {% endblock %}
    </head>

    <body>

        <div class="navigation" id="header">
            {% if user.is_authenticated %}
                <a id="username">Welcome, @{{ user.username }}</a>
            {% endif %}
            <ul>
                {% if user.is_authenticated%}
                    <li><a href="{% url 'posts:category' %}">Categories</a></li>                
                    <li><a href="{% url 'posts:home' %}">Home</a></li>
                    <li><a href="{% url 'posts:user_post' username=user %}">Your Posts</a></li>
                    <li><a href="{% url 'accounts:logout' %}">Log Out</a></li>
                    <li><a href="{% url 'howto' %}">HowTo</a></li>
                {% else %}
                    <li><a href="{% url 'posts:category' %}">Categories</a></li>
                    <li><a href="{% url 'posts:home' %}">Home</a></li>
                    <li><a href="{% url 'accounts:login' %}">Login</a></li>
                    <li><a href="{% url 'howto' %}">HowTo</a></li>
                {% endif %}
            </ul>

            <div id="sideNav" class="side-nav">
                {% if user.is_authenticated %}
                    <span id="closebtn" onclick="closeNav()">&times;</span>
                    <a href="{% url 'posts:category' %}">Categories</a>               
                    <a href="{% url 'posts:home' %}">Home</a>
                    <a href="{% url 'howto' %}">HowTo</a>
                    <a href="{% url 'posts:user_post' username=user %}">Your Posts</a>
                    <a href="{% url 'accounts:logout' %}">Log Out</a>
                {% else %}
                    <span id="closebtn" onclick="closeNav()">&times;</span>
                    <a href="{% url 'posts:category' %}">Categories</a>            
                    <a href="{% url 'posts:home' %}">Home</a>
                    <a href="{% url 'accounts:login' %}">Login</a>
                    <a href="{% url 'howto' %}">HowTo</a>
                {% endif %}
            </div>
            <span class="openbtn" onclick="openNav()">&#9776;</span>
        </div>
        
        <img class="background-image" src="{% static 'images/club-1.jpeg' %}" alt="club" />

        <div>
            {% block content %}
            {% endblock %}
        </div>
        <script src="{% static 'js/sideNav.js' %}"></script>
    </body>

    <footer id="bottom">
        <ul>
            <li><img src="{% static 'images/logos/twitter.png' %}" alt="" id="logo"></li>
            <li><img src="{% static 'images/logos/instagram.png' %}" alt="" id="logo"></li>
            <li><img src="{% static 'images/logos/linkedin.png' %}" alt="" id="logo"></li>
            <li><img src="{% static 'images/logos/githb.png' %}" alt="" id="logo"></li>
            <li><img src="{% static 'images/logos/pin.png' %}" alt="" id="logo"></li>
            <li><img src="{% static 'images/logos/facebook.png' %}" alt="" id="logo"></li>
        </ul>
        <p>&copy; 2022 Social Experiment <br>Made by <b>R.L.H</b> </p>
    </footer>
</html>

templates/posts/add_category.html
{% extends 'base.html' %}
{% load static %} {% load crispy_forms_tags %}

{% block head %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/side.css' %}">
{% endblock %}

{% block content %}
<div class="container" style="margin-top: 100px; margin-bottom: 50px;">
    <div class="container">
        <form method="POST" enctype="multipart/form-data" class="post-form">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" class="btn btn-info" style="margin-top: 50px" value="Add Category"> <br> <br>
            <a class="btn btn-danger" href="{% url 'cancel' %}">Cancel</a>
        </form>
    </div>
</div>
{% endblock %}

templates/posts/category.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/side.css' %}">
{% endblock %}


{% block content %}
<div class="container" style="margin-top: 150px">
    {% if user.is_authenticated %}
        <h1 style="text-align: left; margin-bottom: 25px;">Categories</h1>
        <a href="{% url 'posts:add_category' %}" class="btn btn-info" style="margin-bottom: 50px;">Add Category</a>
    {% else %}
        <h1 style="text-align: left; margin-bottom: 50px;">Categories</h1>
    {% endif %}    
    <div class="container">
        {% for category in category_list %} 
            {% if user.is_authenticated %}
            <div class="row" style="margin: 10px 0;">
                <div class="col-sm">
                    <h3 class="category-text"><a href="{% url 'posts:view_category' category.name|slugify %}" style="color: black; ">{{ category.name|lower }}</a></h3> 
                </div>
                <a href="{% url 'posts:edit_category' pk=category.id %}" class="btn btn-outline-dark" style="margin: 10px;">Edit Category</a>
                <a href="{% url 'posts:remove_category' pk=category.id %}" class="btn btn-outline-danger" style="margin: 10px;">Remove</a>
            </div>
            {% else %}
            <div class="row" style="margin: 10px 0;">
                <div class="col-sm">
                    <h3 class="category-text"><a href="{% url 'posts:view_category' category.name|slugify %}" style="color: black; ">{{ category.name|lower }}</a></h3>
                </div>
            </div>
            {% endif %}
        {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

templates/posts/create_post.html
{% extends 'base.html' %}
{% load static %} {% load crispy_forms_tags %}

{% block head %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/side.css' %}">
{% endblock %}

{% block content %}
<div class="container" style="margin-top: 100px; margin-bottom: 50px; text-transform: uppercase; font-weight: 700;">
    <div class="container">
        <form method="POST" enctype="multipart/form-data" class="post-form">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" class="btn btn-info" style="margin-top: 25px" value="POST">
            <a class="btn btn-danger" style="margin-left: 25px; margin-top: 25px;" href="{% url 'cancel' %}">Cancel</a>
        </form>
    </div>
</div>
{% endblock %}

templates/posts/delete_post.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/side.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <div class="container" style="height: 300px; margin-top: 200px; padding-top: 100px; text-align: center;">
        <form method="POST">
            {% csrf_token %}
            <p>Are you sure you want to delete this post?</p>
            <input type="submit" class="btn btn-danger" value="Delete"> <a class="btn btn-info" href="{% url 'posts:user_post' username=user %}">Go Back</a>
        </form>
    </div>
</div>
{% endblock %}

templates/posts/edit_category.html
{% extends 'base.html' %}
{% load static %} {% load crispy_forms_tags %}

{% block head %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/side.css' %}">
{% endblock %}

{% block content %}
<div class="container" style="margin-top: 75px;">
    <div class="container">
        <form method="POST" enctype="multipart/form-data" class="post-form">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" class="btn btn-info" style="margin-top: 50px" value="Update"> <br> <br>
            <a class="btn btn-danger" href="{% url 'cancel' %}">Cancel</a>
        </form>
    </div>
</div>
{% endblock %}

templates/posts/post_list.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/post_list.css' %}">
{% endblock %}

{% block content %}
<h1>Social Events</h1>
<div>
    {% for post in post_list %}
    <div class="all_posts">
        <img class="image" src="{{ post.flyer.url }}">
        <h3 class="post_user">@{{ post.user.username|lower }}</h3>
        <h3 class="title">{{ post.title }} - {{ post.event_date }}</h3>
        <h4 class="location">{{ post.location }}</h4>
        <p class="caption">{{ post.caption }}</p>
        <p class="category">#{{ post.category }}</p>
        <p class="date-bottom">{{ post.created_at }}</p>
    </div>
    {% endfor %}
    {% if user.is_authenticated %}
        <a class="create-button" href="{% url 'posts:create' %}">Create Post ✏️</a>
    {% endif %}
</div>
{% endblock %}

templates/posts/remove_category.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/side.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <div class="container" style="height: 300px; margin-top: 200px; padding-top: 100px; text-align: center;">
        <form method="POST">
            {% csrf_token %}
            <p>Are you sure you want to delete this category?</p>
            <input type="submit" class="btn btn-danger" value="Delete"> <a class="btn btn-info" href="{% url 'posts:category' %}">Go Back</a>
        </form>
    </div>
</div>
{% endblock %}

templates/posts/update_post.html
{% extends 'base.html' %}
{% load static %} {% load crispy_forms_tags %}

{% block head %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/side.css' %}">
{% endblock %}

{% block content %}
<div class="container" style="margin-top: 75px; margin-bottom: 50px; text-transform: uppercase; font-weight: 700;">
    <div class="container">
        <form method="POST" enctype="multipart/form-data" class="post-form">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" class="btn btn-info" style="margin-top: 50px" value="Update"> <br> <br>
            <a class="btn btn-danger" href="{% url 'cancel' %}">Cancel</a>
        </form>
    </div>
</div>
{% endblock %}

templates/posts/user_posts.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/post_list.css' %}">
{% endblock %}

{% block content %}
<h1>@{{user.username}}'s Posts</h1>
<div>
    {% for post in post_list %}
        {% if user == post.user %}
        <div class="all_posts">
            <img class="image" src="{{ post.flyer.url }}">
            <h3 class="post_user">@{{ post.user.username|lower }}</h3>
            <h3 class="title">{{ post.title }} - {{ post.event_date }}</h3>
            <h4 class="location">{{ post.location }}</h4>
            <p class="caption">{{ post.caption }}</p>
            <p class="category">#{{ post.category }}</p>
            <p class="date-bottom">{{ post.created_at }}</p>
            <a class="icon-update" href="{% url 'posts:update' pk=post.id %}"><img class="more-icon" src="{% static 'images/more.png' %}" alt="icon"></a>   
            <a class="icon-delete" href="{% url 'posts:delete' pk=post.id %}"><img class="close-icon" src="{% static 'images/close.png' %}" alt="icon"></a>   
        </div>
        {% endif %}
    {% endfor %}
    {% if user.is_authenticated %}
        <a class="create-button" href="{% url 'posts:create' %}">Create Post ✏️</a>
    {% endif %}
</div>
{% endblock %}

templates/posts/view_category_posts.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/post_list.css' %}">
{% endblock %}

{% block content %}
<h1>Social Events</h1>
<div>
    {% for post in category_posts %}
        <div class="all_posts">
            <img class="image" src="{{ post.flyer.url }}">
            <h3 class="post_user">@{{ post.user.username|lower }}</h3>
            <h3 class="title">{{ post.title }} - {{ post.event_date }}</h3>
            <h4 class="location">{{ post.location }}</h4>
            <p class="caption">{{ post.caption }}</p>
            <p class="category">#{{ post.category|lower }}</p>
            <p class="date-bottom">{{ post.created_at }}</p>
        </div>
    {% empty %}
        <div class="no-results">
            <h2>No Results</h2>
        </div>
    {% endfor %}
    {% if user.is_authenticated %}
        <a class="create-button" href="{% url 'posts:create' %}">Create Post ✏️</a>
    {% endif %}
</div>
{% endblock %}

templates/social/cancel.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/side.css' %}">
{% endblock %}

{% block content %}
<div class="container" style="margin-top: 150px;">
    <div class="container" style="text-align: center">
        <h3>Are you sure you would like to cancel?</h3> <br>
        <a class="btn btn-danger" href="{% url 'posts:home' %}">Yes</a> <a class="btn btn-success" href="{% url 'posts:user_post' username=user %}">No</a> <br> <br> <br>
    </div>
</div>
{% endblock %}

templates/social/howto.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/side.css' %}">
{% endblock %}

{% block content %}
<div class="container" style="margin-top: 125px;">
    <div class="container" style="text-align: justify;">
        <h4 style="text-align: center; margin-bottom: 25px; font-size: 22px;">This website is intended for persons or promoters who are interested in promoting their event.</h4>
        <div class="container" style="margin-bottom: 50px;">
            <h5>For Promoters</h5>
            <p><strong>Step 1:</strong> Click the login at the top right and you should see a sign up button</p>
            <p><strong>Step 2:</strong> After clicking on the sign up button, enter your credentials. Always try to remember your <strong>password</strong></p>
            <p><strong>Step 3:</strong> You will be then prompted to enter your login credentials once again.</p>
            <p><strong>Step 4:</strong> Lastly, create a <strong>POST</strong> and share your event to the nation.🇹🇹</p>
        </div>
        <div class="container">
            <h5>For Patrons</h5>
            <p>Just sit back, relax and look for an event that suits your needs. 🎤 🥁 🎹 </p>
        </div>
    </div>
</div>
{% endblock %}

templates/social/thanks.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/side.css' %}">
{% endblock %}

{% block content %}
    <h2>Thanks for visiting. <br> Come Back Soon!</h2> <br>
    <a class="thanks-button" href="{% url 'posts:home' %}">Home 🏠</a>
{% endblock %}

templates/social/welcome.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/side.css' %}">
{% endblock %}

{% block content %}
    <h2>You are now signed in as <br> @{{ user.username }} <br> Welcome!</h2> <br>
    <a class="welcome-button" href="{% url 'posts:home' %}">Home 🏠</a>
{% endblock %}